#!/usr/bin/env node
// Turns the SPC prototype snapshot into insert SQL for D1.
//   node import.mjs ../data/spc-state-2026-09-13.json > seed.sql
// People get fresh tokens (the prototype had a shared PIN, redacted). The tokens are written to
// SECRETS.txt next to this file (gitignored) so main can hand out the personal links.
import { readFileSync, writeFileSync } from 'node:fs'
import { randomBytes } from 'node:crypto'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const file = process.argv[2] || join(dirname(fileURLToPath(import.meta.url)), '..', 'data', 'spc-state-2026-09-13.json')
const snap = JSON.parse(readFileSync(file, 'utf8'))

const ROLE_CODES = {
  lg: 'lead guitar', lead: 'lead guitar', 'lead guitar': 'lead guitar',
  rg: 'rhythm guitar', ag: 'rhythm guitar', rhythm: 'rhythm guitar', 'rhythm guitar': 'rhythm guitar', acoustic: 'rhythm guitar',
  bass: 'bass', b: 'bass',
  drums: 'drums', d: 'drums', dr: 'drums',
  keys: 'keys', k: 'keys',
  v1: 'vocals 1', v2: 'vocals 2', v3: 'vocals 3', 'vocals 1': 'vocals 1', 'vocals 2': 'vocals 2', 'vocals 3': 'vocals 3',
  vox: 'vocals 1', vocals: 'vocals 1',
  sound: 'sound', snd: 'sound', pa: 'sound',
  proj: 'projection', projection: 'projection', pp: 'projection', words: 'projection'
}
const KINDS = { am: 'am', pm: 'pm', prac: 'practice', practice: 'practice', special: 'special', sp: 'special' }

const ALPHABET = 'abcdefghijkmnpqrstuvwxyz23456789'
const token = (n = 24) => [...randomBytes(n)].map(b => ALPHABET[b % ALPHABET.length]).join('')
const q = (v) => v == null ? 'NULL' : typeof v === 'number' ? String(v) : `'${String(v).replace(/'/g, "''")}'`
const role = (code) => { const r = ROLE_CODES[String(code).toLowerCase()]; if (!r) throw new Error(`Unknown role code in snapshot: ${code}`); return r }
const created = new Date().toISOString()

const out = ['-- Generated by worker/import.mjs from ' + file.split('/').pop() + ' on ' + created]
const secrets = [`# Personal links (generated ${created}). Do not commit.`]

// The leader: Alexander organises the rota. Anyone the snapshot marks leader also counts.
const leaderIds = new Set(snap.team.filter(p => p.leader || p.name === 'Alexander Power').map(p => p.id))

for (const p of snap.team) {
  const t = token()
  const roles = (p.roles || []).map(role)
  const isLeader = leaderIds.has(p.id) ? 1 : 0
  out.push(`INSERT INTO people(id, name, roles, token, is_leader, phone, created) VALUES (${q(p.id)}, ${q(p.name)}, ${q(JSON.stringify(roles))}, ${q(t)}, ${isLeader}, ${q(p.phone || '')}, ${q(created)});`)
  secrets.push(`${p.name}${isLeader ? ' (leader)' : ''}: /#/${isLeader ? 'lead' : 'me'}/${t}`)
}
for (const s of snap.songs) {
  out.push(`INSERT INTO songs(id, title, artist, key, bpm, chart, video, notes, last_used, rev) VALUES (${q(s.id)}, ${q(s.title)}, ${q(s.artist || '')}, ${q(s.key || '')}, ${s.bpm == null || s.bpm === '' ? 'NULL' : Number(s.bpm)}, ${q(s.chart || '')}, ${q(s.video || '')}, ${q(s.notes || '')}, ${q(s.last || '')}, 1);`)
}
for (const s of snap.services) {
  const kind = KINDS[s.type] || 'special'
  out.push(`INSERT INTO services(id, date, time, kind, title, notes, rev) VALUES (${q(s.id)}, ${q(s.date)}, ${q(s.time || '')}, ${q(kind)}, ${q(s.title || '')}, ${q(s.notes || '')}, 1);`)
  for (const pid of s.out || []) out.push(`INSERT OR IGNORE INTO away(person_id, date) VALUES (${q(pid)}, ${q(s.date)});`)
  for (const [code, pid] of Object.entries(s.assign || {})) {
    if (!pid) continue
    if ((s.out || []).includes(pid)) continue // away wins; never seed a contradiction
    out.push(`INSERT INTO assignments(service_id, role, person_id) VALUES (${q(s.id)}, ${q(role(code))}, ${q(pid)});`)
  }
  let pos = 1
  for (const e of s.set || []) {
    out.push(`INSERT INTO set_entries(id, service_id, position, song_id, key, lead_person_id, note) VALUES (${q(e.id || (s.id + '-' + pos))}, ${q(s.id)}, ${pos++}, ${q(e.songId)}, ${q(e.key || '')}, ${e.leadId ? q(e.leadId) : 'NULL'}, ${q(e.note || '')});`)
  }
}
for (const c of snap.channels) {
  out.push(`INSERT INTO channels(id, ch, src, inp, note) VALUES (${q(c.id)}, ${Number(c.ch)}, ${q(c.src || '')}, ${q(c.inp || '')}, ${q(c.note || '')});`)
}
for (const i of snap.issues || []) {
  out.push(`INSERT INTO desk_notes(id, person_id, text, created, resolved) VALUES (${q(i.id || token(6))}, NULL, ${q(i.text || String(i))}, ${q(i.created || created)}, ${i.resolved ? 1 : 0});`)
}

process.stdout.write(out.join('\n') + '\n')
// SECRETS.txt is the LIVE links file. Local runs (tests) must not overwrite it: set ROTA_SECRETS to another path.
const secretsPath = process.env.ROTA_SECRETS || join(dirname(fileURLToPath(import.meta.url)), 'SECRETS.txt')
writeFileSync(secretsPath, secrets.join('\n') + '\n')
console.error(`wrote ${out.length - 1} rows; personal links in ${secretsPath}`)
